Repository laminas/documentation-theme, pull requests merged in 2022-12, with the labels that each got.

#88 Adds PyMdown extension Snippets to MkDocs update script
  update_mkdocs_yml.py
Labels: Enhancement

#89 Updates do-we-build-and-if-so-what script to user and prefer `DEPLOY_TOKEN`
  github-actions/docs/do-we-build-and-if-so-what.php
Labels: Bug

#91 Use token authentication
  github-actions/docs/entrypoint.sh
Labels: Bug

#92 Use x-access-token format
  github-actions/docs/entrypoint.sh
Labels: Bug

#93 Updates readme file of the workflow to use `GITHUB_TOKEN`
  github-actions/docs/README.md
Labels: Bug, Documentation
